export const testing = () => {
  try {
    return {
      result: [],
    };
  } catch (error) {
    return {
      error: "drror occured",
    };
  }
};
